name: PR Workflow

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # set the default directory for all "run" commands to "/chakra", which
        # is the directory where the repo code will be checked out to. we put
        # the code in /chakra so that the CRA templates build step can build
        # the projects in a directory outside of the repo tree, which is needed
        # because CRA throws errors due to conflicting package versions
        working-directory: chakra
    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout
        uses: actions/checkout@v1
        with:
          path: "chakra"

      - name: Enable node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Load Yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Build packages
        run: yarn build

      - name: Build CRA templates
        run: yarn build:templates ../cra-templates

      - name: Lint types and code
        run: yarn lint

      - name: Run tests
        run: yarn test
